{% set name = "mktestdocs" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mktestdocs-{{ version }}.tar.gz
  sha256: 44142b98223f02c7ba4629790d9ee83031fd4d8855577c6fbfc23103421d3872

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - mktestdocs
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not test_class and not test_big_files_good and not test_big_file_independant and not test_files_unmarked_language_default and not test_files_unmarked_language_bash and not test_override_executor and not test_readme" tests
  requires:
    - pip
    - pytest >=4.0.2

about:
  home: https://github.com/koaning/mktestdocs
  license: Apache-2.0
  license_file: LICENSE
  summary: Run pytest against markdown files/docstrings.

extra:
  recipe-maintainers:
    - thewchan
